name: Generate auto.yml

on:
  schedule:
    - cron: '1 */4 * * *'
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须要有写入权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip3 install pyYAML requests tqdm
          [ -f requirements.txt ] && pip install -r requirements.txt

      - name: Collect proxies
        run: |
          python -u subscribe/collect.py -s

      - name: Debug files
        run: ls -R data/  # 确认文件已生成

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push
        run: |
          # 重置所有未跟踪和修改的文件（确保工作目录干净）
          git reset --hard
          git clean -fd

          # 拉取最新代码（避免冲突）
          git pull origin main

          # 重新添加文件并提交
          git add data/
          git commit -m "Add generated output.yaml (Automated)"

          # 强制推送（谨慎使用，适用于自动化场景）
          git push origin main
