name: Docker Image CI

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build and push Docker image
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH_NAME" == "main" ]; then
            # 构建多架构镜像并推送
            docker buildx build --push \
              --platform linux/amd64,linux/arm64/v8 \
              --tag ${{ secrets.DOCKER_USERNAME }}/subbygithub:$(date +%Y%m%d) \
              --tag ${{ secrets.DOCKER_USERNAME }}/subbygithub:latest \
              -f Dockerfile .
          else
            # 对于非主分支，仅推送当前分支名称的标签
            docker buildx build --push \
              --platform linux/amd64,linux/arm64/v8 \
              --tag ${{ secrets.DOCKER_USERNAME }}/subbygithub:$BRANCH_NAME \
              -f Dockerfile .
          fi

      - name: Inspect buildx builder
        run: docker buildx inspect --bootstrap

